/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import datos.ipersonaimpl;
import java.util.ArrayList;
import datos.tipos;
import datos.persona;

/**
 *
 * @author User
 */
public class registro_persona extends javax.swing.JFrame {
    
     public void tiposdocumento(){
        cbtipodocumento.removeAllItems();
        ArrayList <String> lista=new ArrayList();
        lista=tipos.tipodocumento();
        for(int i=0;i<lista.size();i++){
            cbtipodocumento.addItem(lista.get(i));
        }
    }

    /**
     * Creates new form registro_persona
     */
    public registro_persona() {
        initComponents();
        tiposdocumento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtapellido = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        lbtitulo = new javax.swing.JLabel();
        cbtipodocumento = new javax.swing.JComboBox<>();
        lbtipodocumento = new javax.swing.JLabel();
        lbdocumento = new javax.swing.JLabel();
        lbnombre = new javax.swing.JLabel();
        lbapellido = new javax.swing.JLabel();
        cbroll = new javax.swing.JComboBox<>();
        lbdireccion = new javax.swing.JLabel();
        lbtelefono = new javax.swing.JLabel();
        lbtipopersona = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txtdocumento = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        lbimagen = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbmensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 182, 139, -1));
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 208, 139, -1));

        lbtitulo.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lbtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitulo.setText("REGISTRO DE PERSONA");
        getContentPane().add(lbtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 11, 273, 47));

        cbtipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbtipodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 104, 139, -1));

        lbtipodocumento.setText("Tipo de documento");
        getContentPane().add(lbtipodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 107, -1, -1));

        lbdocumento.setText("Documento");
        getContentPane().add(lbdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 133, -1, -1));

        lbnombre.setText("Nombres");
        getContentPane().add(lbnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 159, -1, -1));

        lbapellido.setText("Apellidos");
        getContentPane().add(lbapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 185, -1, -1));

        cbroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador", "Empleado" }));
        cbroll.setEnabled(false);
        getContentPane().add(cbroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 263, 139, -1));

        lbdireccion.setText("Direccion");
        getContentPane().add(lbdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 211, -1, -1));

        lbtelefono.setText("Telefono");
        getContentPane().add(lbtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 237, -1, -1));

        lbtipopersona.setText("Tipo de persona");
        getContentPane().add(lbtipopersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 266, -1, -1));
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 234, 139, -1));

        txtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 130, 139, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 156, 139, -1));

        lbimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/personas.png"))); // NOI18N
        getContentPane().add(lbimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 314, -1, -1));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 314, -1, -1));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 314, -1, -1));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 314, -1, -1));

        lbmensaje.setForeground(new java.awt.Color(255, 0, 51));
        lbmensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 289, 234, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/AdobeStock_327373745.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtdocumento.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        lbmensaje.setText("");
        tiposdocumento();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        // TODO add your handling code here:
        persona p = new persona(txtnombre.getText(),txtapellido.getText(),cbtipodocumento.getSelectedItem().toString(),txtdocumento.getText(),txtdireccion.getText(),Integer.parseInt(txttelefono.getText()),cbroll.getSelectedItem().toString());
            ipersonaimpl ip = new ipersonaimpl();
            ip.insertarpersona(p);
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ipersonaimpl ip = new ipersonaimpl();
        ip.eliminarpersona(txtdocumento.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox<String> cbroll;
    private javax.swing.JComboBox<String> cbtipodocumento;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbapellido;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbdocumento;
    private javax.swing.JLabel lbimagen;
    private javax.swing.JLabel lbmensaje;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbtelefono;
    private javax.swing.JLabel lbtipodocumento;
    private javax.swing.JLabel lbtipopersona;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
